name: Docker CI
on: [push]
jobs:
    build:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                python-version: 3.8
            - run: docker build -t aes .